version: '3'

services:
  player-1:
    build:
      context: ./player-1
    networks:
      my-network:
    ports:
      - "8000:80"
    volumes:
      - ./player-1/laravel-app:/var/www/html
      - ./player-1/apache:/etc/apache2/sites-available
      - ./player-1/supervisor:/etc/supervisor/conf.d

  player-2:
    build:
      context: ./player-2
    networks:
      my-network:
    ports:
      - "8001:80"
    volumes:
      - ./player-2/laravel-app:/var/www/html
      - ./player-2/apache:/etc/apache2/sites-available
      - ./player-2/supervisor:/etc/supervisor/conf.d

  websockets-server:
    build:
      context: ./websockets-server
    networks:
      my-network:
        ipv4_address: 172.31.0.4
    volumes:
      - ./websockets-server/laravel-app:/var/www/html
      - ./websockets-server/apache:/etc/apache2/sites-available
      - ./websockets-server/supervisor:/etc/supervisor/conf.d

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16